### PR TITLE
Revamp base classes

### PR DESCRIPTION
**Pull request by nmay231**
Main additions/changes
- Added support for mods to Champion()s (formerly the Player() class)
- Renamed Player to Champion and (re)added Player class for players themselves
- Put main components (Game, Player, Champion, etc) into a separate file and renamed 'flat land.py' to 'main.py'
- Added an exceptions file for game exceptions (IllegalMove)

### CODE REVIEW

**Comment by nmay231** [comment]
Also added 'champs/' folder. Each file in that folder will contain the code for each Champ.

**Comment by nmay231** [comment]
I can resolve the conflicts if you have no issues with the merge.

**Comment by calebmrose00** [comment]
go ahead.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nmay231** [comment]
Merged locally.

**Pull request closed without merging**
